name: gdgm_lins
description: gdgm-OA
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  dio_cookie_manager: ^2.0.0
  html: ^0.15.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
